package canon

type CommandInfo struct {
	Name        string   `json:"name"`
	Purpose     string   `json:"purpose"`
	Mutating    bool     `json:"mutating"`
	HasDryRun   bool     `json:"has_dry_run"`
	Safety      string   `json:"safety"`
	Selectors   []string `json:"selectors,omitempty"`
	Examples    []string `json:"examples"`
	NextCommand []string `json:"next_commands,omitempty"`
}

func commandRegistry() []CommandInfo {
	return []CommandInfo{
		{
			Name:      "commands",
			Purpose:   "Return the machine-readable command registry with safety and composition metadata.",
			Safety:    "read-only",
			Examples:  []string{"canon commands"},
			Mutating:  false,
			HasDryRun: false,
		},
		{
			Name:      "doctor",
			Purpose:   "Check whether ADR and SPEC storage is present and parseable.",
			Safety:    "read-only",
			Examples:  []string{"canon doctor"},
			Mutating:  false,
			HasDryRun: false,
		},
		{
			Name:      "adr init",
			Purpose:   "Create the ADR directory if it does not exist.",
			Safety:    "write: creates directory only",
			Examples:  []string{"canon adr init --dry-run", "canon adr init"},
			Mutating:  true,
			HasDryRun: true,
		},
		{
			Name:      "spec init",
			Purpose:   "Create the SPEC directory if it does not exist.",
			Safety:    "write: creates directory only",
			Examples:  []string{"canon spec init --dry-run", "canon spec init"},
			Mutating:  true,
			HasDryRun: true,
		},
		{
			Name:        "adr new",
			Purpose:     "Create a new ADR markdown file with parseable metadata. ADRs capture architecture decisions.",
			Safety:      "write: creates one markdown file",
			Selectors:   []string{"--title", "--status", "--tags"},
			Examples:    []string{`canon adr new --title "Use SQLite for local index" --status proposed --dry-run`, `canon adr new --title "Use SQLite for local index" --context "Need local querying" --decision "Use SQLite"`},
			NextCommand: []string{"canon adr list", "canon show --id ADR-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "spec new",
			Purpose:     "Create a new SPEC markdown file with parseable metadata. SPECs capture functional requirements.",
			Safety:      "write: creates one markdown file",
			Selectors:   []string{"--title", "--status", "--tags"},
			Examples:    []string{`canon spec new --title "Local query index" --requirements "Return ADRs by tag." --acceptance "list --tag storage works." --dry-run`},
			NextCommand: []string{"canon spec list", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "list",
			Purpose:     "List ADR and SPEC summaries together in deterministic order.",
			Safety:      "read-only",
			Selectors:   []string{"--status", "--tag"},
			Examples:    []string{"canon list", "canon list --status accepted"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001", "canon search --query text"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "adr list",
			Purpose:     "List ADR summaries in deterministic order.",
			Safety:      "read-only",
			Selectors:   []string{"--status", "--tag"},
			Examples:    []string{"canon adr list", "canon adr list --status accepted"},
			NextCommand: []string{"canon show --id ADR-0001", "canon adr search --query text"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "spec list",
			Purpose:     "List SPEC summaries in deterministic order.",
			Safety:      "read-only",
			Selectors:   []string{"--status", "--tag"},
			Examples:    []string{"canon spec list", "canon spec list --tag storage"},
			NextCommand: []string{"canon show --id SPEC-0001", "canon spec search --query text"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "show",
			Purpose:     "Return one ADR or SPEC with metadata and content.",
			Safety:      "read-only",
			Selectors:   []string{"--id"},
			Examples:    []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			NextCommand: []string{"canon append --id ADR-0001 --title Note --body ... --dry-run", "canon append --id SPEC-0001 --title Note --body ... --dry-run"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "search",
			Purpose:     "Search title, tags, status, kind, and markdown body across ADRs and SPECs.",
			Safety:      "read-only",
			Selectors:   []string{"--query", "--status", "--tag"},
			Examples:    []string{`canon search --query "database"`, "canon search --status deprecated"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "adr search",
			Purpose:     "Search title, tags, status, and markdown body across ADRs only.",
			Safety:      "read-only",
			Selectors:   []string{"--query", "--status", "--tag"},
			Examples:    []string{`canon adr search --query "database"`},
			NextCommand: []string{"canon show --id ADR-0001"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "spec search",
			Purpose:     "Search title, tags, status, and markdown body across SPECs only.",
			Safety:      "read-only",
			Selectors:   []string{"--query", "--status", "--tag"},
			Examples:    []string{"canon spec search --query requirements"},
			NextCommand: []string{"canon show --id SPEC-0001"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "accept",
			Purpose:     "Mark an ADR or SPEC as accepted.",
			Safety:      "write: updates one document metadata block and appends history",
			Selectors:   []string{"--id", "--reason"},
			Examples:    []string{"canon accept --id ADR-0001 --reason \"Approved by the team.\" --dry-run", "canon accept --id SPEC-0001 --reason \"Requirements approved.\" --dry-run"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "reject",
			Purpose:     "Mark an ADR or SPEC as rejected.",
			Safety:      "write: updates one document metadata block and appends history",
			Selectors:   []string{"--id", "--reason"},
			Examples:    []string{"canon reject --id ADR-0001 --reason \"Chose a different approach.\" --dry-run", "canon reject --id SPEC-0001 --reason \"Requirements changed.\" --dry-run"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "supersede",
			Purpose:     "Mark an ADR or SPEC as superseded by another document of the same kind.",
			Safety:      "write: updates two document metadata blocks and appends history",
			Selectors:   []string{"--id", "--by", "--reason"},
			Examples:    []string{"canon supersede --id ADR-0001 --by ADR-0002 --reason \"Replaced by current architecture\" --dry-run", "canon supersede --id SPEC-0001 --by SPEC-0002 --reason \"Requirements split.\" --dry-run"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "deprecate",
			Purpose:     "Mark an ADR or SPEC as deprecated without a direct replacement.",
			Safety:      "write: updates one document metadata block and appends history",
			Selectors:   []string{"--id", "--reason"},
			Examples:    []string{"canon deprecate --id ADR-0001 --reason \"No longer used\" --dry-run", "canon deprecate --id SPEC-0001 --reason \"Requirements moved.\" --dry-run"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "append",
			Purpose:     "Append a dated appendix section to an ADR or SPEC.",
			Safety:      "write: appends markdown to one document",
			Selectors:   []string{"--id", "--title", "--body"},
			Examples:    []string{"canon append --id ADR-0001 --title \"2026 review\" --body \"Still valid.\" --dry-run", "canon append --id SPEC-0001 --title Review --body \"Requirements still apply.\" --dry-run"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:      "skill",
			Purpose:   "Print bundled agent instructions for using this CLI safely and effectively.",
			Safety:    "read-only",
			Examples:  []string{"canon skill"},
			Mutating:  false,
			HasDryRun: false,
		},
		{
			Name:        "skill install",
			Purpose:     "Install the CANON agent skill into a repository-local skill directory.",
			Safety:      "write: creates a skill directory and SKILL.md",
			Selectors:   []string{"--skill-dir"},
			Examples:    []string{"canon skill install --dry-run", "canon skill install", "canon skill install --skill-dir .agents/skills/canon --dry-run"},
			NextCommand: []string{"canon skill update --dry-run", "canon commands"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "skill update",
			Purpose:     "Update an installed CANON agent skill when it is unchanged or explicitly forced.",
			Safety:      "write: updates one SKILL.md",
			Selectors:   []string{"--skill-dir", "--force"},
			Examples:    []string{"canon skill update --dry-run", "canon skill update", "canon skill update --force --dry-run"},
			NextCommand: []string{"canon commands"},
			Mutating:    true,
			HasDryRun:   true,
		},
	}
}
