package canon

type CommandInfo struct {
	Name        string   `json:"name"`
	Purpose     string   `json:"purpose"`
	Mutating    bool     `json:"mutating"`
	HasDryRun   bool     `json:"has_dry_run"`
	Safety      string   `json:"safety"`
	Selectors   []string `json:"selectors,omitempty"`
	Examples    []string `json:"examples"`
	NextCommand []string `json:"next_commands,omitempty"`
}

func commandRegistry() []CommandInfo {
	return []CommandInfo{
		{
			Name:      "commands",
			Purpose:   "Return the machine-readable command registry with safety and composition metadata.",
			Safety:    "read-only",
			Examples:  []string{"canon commands"},
			Mutating:  false,
			HasDryRun: false,
		},
		{
			Name:      "doctor",
			Purpose:   "Check whether ADR, SPEC, and domain storage is present and parseable, and flag domain-model integrity problems (duplicate accepted titles, references to superseded or deprecated entries).",
			Safety:    "read-only",
			Examples:  []string{"canon doctor"},
			Mutating:  false,
			HasDryRun: false,
		},
		{
			Name:        "validate",
			Purpose:     "Run the full corpus integrity check catalog (SPEC-0001): malformed files, duplicate ids, broken references, reciprocity, status and date validity, and kind/id/directory coherence. Never mutates; exit 4 on errors, or on warnings with --strict.",
			Safety:      "read-only",
			Selectors:   []string{"--id", "--strict"},
			Examples:    []string{"canon validate", "canon validate --strict", "canon validate --id ADR-0001"},
			NextCommand: []string{"canon doctor", "canon show --id ADR-0001"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "adr validate",
			Purpose:     "Run the corpus integrity checks scoped to the ADR directory.",
			Safety:      "read-only",
			Selectors:   []string{"--strict"},
			Examples:    []string{"canon adr validate"},
			NextCommand: []string{"canon validate"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "spec validate",
			Purpose:     "Run the corpus integrity checks scoped to the SPEC directory.",
			Safety:      "read-only",
			Selectors:   []string{"--strict"},
			Examples:    []string{"canon spec validate"},
			NextCommand: []string{"canon validate"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "domain validate",
			Purpose:     "Run the corpus integrity checks scoped to the domain entry directory.",
			Safety:      "read-only",
			Selectors:   []string{"--strict"},
			Examples:    []string{"canon domain validate"},
			NextCommand: []string{"canon validate"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:      "adr init",
			Purpose:   "Create the ADR directory if it does not exist.",
			Safety:    "write: creates directory only",
			Examples:  []string{"canon adr init --dry-run", "canon adr init"},
			Mutating:  true,
			HasDryRun: true,
		},
		{
			Name:      "spec init",
			Purpose:   "Create the SPEC directory if it does not exist.",
			Safety:    "write: creates directory only",
			Examples:  []string{"canon spec init --dry-run", "canon spec init"},
			Mutating:  true,
			HasDryRun: true,
		},
		{
			Name:      "domain init",
			Purpose:   "Create the domain entry directory if it does not exist.",
			Safety:    "write: creates directory only",
			Examples:  []string{"canon domain init --dry-run", "canon domain init"},
			Mutating:  true,
			HasDryRun: true,
		},
		{
			Name:        "adr new",
			Purpose:     "Create a new ADR markdown file with parseable metadata. ADRs capture architecture decisions.",
			Safety:      "write: creates one markdown file",
			Selectors:   []string{"--title", "--status", "--tags"},
			Examples:    []string{`canon adr new --title "Use SQLite for local index" --status proposed --dry-run`, `canon adr new --title "Use SQLite for local index" --context "Need local querying" --decision "Use SQLite"`},
			NextCommand: []string{"canon adr list", "canon show --id ADR-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "spec new",
			Purpose:     "Create a new SPEC markdown file with parseable metadata. SPECs capture functional requirements.",
			Safety:      "write: creates one markdown file",
			Selectors:   []string{"--title", "--status", "--tags"},
			Examples:    []string{`canon spec new --title "Local query index" --requirements "Return ADRs by tag." --acceptance "list --tag storage works." --dry-run`},
			NextCommand: []string{"canon spec list", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "domain new",
			Purpose:     "Create a new domain entry markdown file with parseable metadata. Domain entries define one canonical concept each: its definition, avoided terms with reasons, and relationships.",
			Safety:      "write: creates one markdown file",
			Selectors:   []string{"--title", "--status", "--tags", "--definition", "--avoid", "--relationships"},
			Examples:    []string{`canon domain new --title "ADR" --definition "A dated, narrowly-scoped architecture commitment." --avoid "design doc: too broad; ticket: tracks work, not decisions" --dry-run`},
			NextCommand: []string{"canon domain list", "canon show --id DM-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "list",
			Purpose:     "List ADR, SPEC, and domain entry summaries together in deterministic order.",
			Safety:      "read-only",
			Selectors:   []string{"--status", "--tag"},
			Examples:    []string{"canon list", "canon list --status accepted", "canon --format context list --status accepted"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001", "canon show --id DM-0001", "canon search --query text"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "adr list",
			Purpose:     "List ADR summaries in deterministic order.",
			Safety:      "read-only",
			Selectors:   []string{"--status", "--tag"},
			Examples:    []string{"canon adr list", "canon adr list --status accepted", "canon --format context adr list --status accepted"},
			NextCommand: []string{"canon show --id ADR-0001", "canon adr search --query text"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "spec list",
			Purpose:     "List SPEC summaries in deterministic order.",
			Safety:      "read-only",
			Selectors:   []string{"--status", "--tag"},
			Examples:    []string{"canon spec list", "canon spec list --tag storage", "canon --format context spec list --status accepted"},
			NextCommand: []string{"canon show --id SPEC-0001", "canon spec search --query text"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "domain list",
			Purpose:     "List domain entry summaries in deterministic order.",
			Safety:      "read-only",
			Selectors:   []string{"--status", "--tag"},
			Examples:    []string{"canon domain list", "canon domain list --status accepted", "canon --format context domain list --status accepted"},
			NextCommand: []string{"canon show --id DM-0001", "canon domain search --query text"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "show",
			Purpose:     "Return one ADR, SPEC, or domain entry with metadata and content.",
			Safety:      "read-only",
			Selectors:   []string{"--id"},
			Examples:    []string{"canon show --id ADR-0001", "canon show --id SPEC-0001", "canon show --id DM-0001"},
			NextCommand: []string{"canon append --id ADR-0001 --title Note --body ... --dry-run", "canon append --id SPEC-0001 --title Note --body ... --dry-run"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "search",
			Purpose:     "Search title, tags, status, kind, and markdown body across ADRs, SPECs, and domain entries.",
			Safety:      "read-only",
			Selectors:   []string{"--query", "--status", "--tag"},
			Examples:    []string{`canon search --query "database"`, "canon search --status deprecated"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "adr search",
			Purpose:     "Search title, tags, status, and markdown body across ADRs only.",
			Safety:      "read-only",
			Selectors:   []string{"--query", "--status", "--tag"},
			Examples:    []string{`canon adr search --query "database"`},
			NextCommand: []string{"canon show --id ADR-0001"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "spec search",
			Purpose:     "Search title, tags, status, and markdown body across SPECs only.",
			Safety:      "read-only",
			Selectors:   []string{"--query", "--status", "--tag"},
			Examples:    []string{"canon spec search --query requirements"},
			NextCommand: []string{"canon show --id SPEC-0001"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "domain search",
			Purpose:     "Search title, tags, status, and markdown body across domain entries only.",
			Safety:      "read-only",
			Selectors:   []string{"--query", "--status", "--tag"},
			Examples:    []string{`canon domain search --query "cancellation"`},
			NextCommand: []string{"canon show --id DM-0001"},
			Mutating:    false,
			HasDryRun:   false,
		},
		{
			Name:        "accept",
			Purpose:     "Mark an ADR, SPEC, or domain entry as accepted.",
			Safety:      "write: updates one document metadata block and appends history",
			Selectors:   []string{"--id", "--reason"},
			Examples:    []string{"canon accept --id ADR-0001 --reason \"Approved by the team.\" --dry-run", "canon accept --id SPEC-0001 --reason \"Requirements approved.\" --dry-run"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "reject",
			Purpose:     "Mark an ADR, SPEC, or domain entry as rejected.",
			Safety:      "write: updates one document metadata block and appends history",
			Selectors:   []string{"--id", "--reason"},
			Examples:    []string{"canon reject --id ADR-0001 --reason \"Chose a different approach.\" --dry-run", "canon reject --id SPEC-0001 --reason \"Requirements changed.\" --dry-run"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "supersede",
			Purpose:     "Mark an ADR, SPEC, or domain entry as superseded by another document of the same kind.",
			Safety:      "write: updates two document metadata blocks and appends history",
			Selectors:   []string{"--id", "--by", "--reason"},
			Examples:    []string{"canon supersede --id ADR-0001 --by ADR-0002 --reason \"Replaced by current architecture\" --dry-run", "canon supersede --id SPEC-0001 --by SPEC-0002 --reason \"Requirements split.\" --dry-run"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "deprecate",
			Purpose:     "Mark an ADR, SPEC, or domain entry as deprecated without a direct replacement.",
			Safety:      "write: updates one document metadata block and appends history",
			Selectors:   []string{"--id", "--reason"},
			Examples:    []string{"canon deprecate --id ADR-0001 --reason \"No longer used\" --dry-run", "canon deprecate --id SPEC-0001 --reason \"Requirements moved.\" --dry-run"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "append",
			Purpose:     "Append a dated appendix section to an ADR, SPEC, or domain entry.",
			Safety:      "write: appends markdown to one document",
			Selectors:   []string{"--id", "--title", "--body"},
			Examples:    []string{"canon append --id ADR-0001 --title \"2026 review\" --body \"Still valid.\" --dry-run", "canon append --id SPEC-0001 --title Review --body \"Requirements still apply.\" --dry-run"},
			NextCommand: []string{"canon show --id ADR-0001", "canon show --id SPEC-0001"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:      "skill",
			Purpose:   "Return the bundled skill asset catalog with names, kinds, versions, hashes, and target paths.",
			Safety:    "read-only",
			Examples:  []string{"canon skill"},
			Mutating:  false,
			HasDryRun: false,
		},
		{
			Name:        "skill install",
			Purpose:     "Install all bundled skill assets and selected subagent components into a repository.",
			Safety:      "write: creates skill payload files and target-specific agent files",
			Selectors:   []string{"--skill-dir", "--only", "--agent"},
			Examples:    []string{"canon skill install --dry-run", "canon skill install", "canon skill install --only canon --dry-run", "canon skill install --agent claude --dry-run"},
			NextCommand: []string{"canon skill update --dry-run", "canon commands"},
			Mutating:    true,
			HasDryRun:   true,
		},
		{
			Name:        "skill update",
			Purpose:     "Refresh every installed managed bundle file, refusing local modifications unless forced.",
			Safety:      "write: updates managed skill payload files and target-specific agent files",
			Selectors:   []string{"--skill-dir", "--only", "--agent", "--force"},
			Examples:    []string{"canon skill update --dry-run", "canon skill update", "canon skill update --only canon-record-gate --dry-run", "canon skill update --force --dry-run"},
			NextCommand: []string{"canon commands"},
			Mutating:    true,
			HasDryRun:   true,
		},
	}
}
